/**
 * ResonantGenesis Chain Client SDK
 * TypeScript client for interacting with Coordination Chain contracts
 */

import { ethers, Contract, Wallet, Provider } from 'ethers';

// Contract ABIs (simplified - full ABIs generated by Hardhat)
const IDENTITY_REGISTRY_ABI = [
  "function register(bytes32 dsid, uint8 idType, bytes32 publicKeyHash, string metadataUri)",
  "function updateMetadata(bytes32 dsid, string metadataUri)",
  "function rotateKey(bytes32 dsid, bytes32 newPublicKeyHash, string reason)",
  "function setRecoveryKey(bytes32 dsid, bytes32 recoveryKeyHash)",
  "function suspend(bytes32 dsid)",
  "function reactivate(bytes32 dsid)",
  "function revoke(bytes32 dsid)",
  "function getIdentity(bytes32 dsid) view returns (tuple(bytes32 dsid, uint8 idType, uint8 status, bytes32 publicKeyHash, address evmAddress, string metadataUri, uint256 createdAt, uint256 updatedAt, uint256 nonce))",
  "function isActive(bytes32 dsid) view returns (bool)",
  "function verifyKey(bytes32 dsid, bytes32 publicKeyHash) view returns (bool)",
  "event IdentityRegistered(bytes32 indexed dsid, uint8 idType, address indexed evmAddress, uint256 timestamp)",
  "event KeyRotated(bytes32 indexed dsid, bytes32 oldKeyHash, bytes32 newKeyHash, string reason, uint256 timestamp)"
];

const AGENT_REGISTRY_ABI = [
  "function publish(bytes32 manifestHash, bytes32 codeChecksum, string sourceUri, string manifestUri, bytes32 ownerDsid, uint8 trustTier, bytes32 parentHash, string category)",
  "function updateManifest(bytes32 manifestHash, string newManifestUri, bytes32 ownerDsid)",
  "function publishVersion(bytes32 manifestHash, string version, string changelog, bytes32 ownerDsid)",
  "function transfer(bytes32 manifestHash, bytes32 fromDsid, bytes32 toDsid)",
  "function deprecate(bytes32 manifestHash, bytes32 ownerDsid)",
  "function getAgent(bytes32 manifestHash) view returns (tuple(bytes32 manifestHash, bytes32 codeChecksum, string sourceUri, string manifestUri, bytes32 ownerDsid, uint8 trustTier, uint8 status, bytes32 parentHash, string category, uint256 publishedAt, uint256 updatedAt, uint256 executionCount))",
  "function isActive(bytes32 manifestHash) view returns (bool)",
  "function getAgentsByOwner(bytes32 ownerDsid) view returns (bytes32[])",
  "function getAgentsByCategory(string category) view returns (bytes32[])",
  "function verifyCode(bytes32 manifestHash, bytes32 checksum) view returns (bool)",
  "event AgentPublished(bytes32 indexed manifestHash, bytes32 indexed ownerDsid, string sourceUri, uint8 trustTier, uint256 timestamp)",
  "event AgentTransferred(bytes32 indexed manifestHash, bytes32 indexed fromDsid, bytes32 indexed toDsid, uint256 timestamp)"
];

const MEMORY_ANCHORS_ABI = [
  "function anchor(bytes32 contentHash, bytes32 ownerDsid, bytes32 agentDsid, uint8 memoryType, string storageUri, bytes32 parentHash)",
  "function anchorBatch(bytes32[] contentHashes, bytes32 ownerDsid, bytes32 agentDsid, uint8 memoryType, string storageUri)",
  "function revokeAnchor(bytes32 contentHash, bytes32 ownerDsid)",
  "function getAnchor(bytes32 contentHash) view returns (tuple(bytes32 contentHash, bytes32 ownerDsid, bytes32 agentDsid, uint8 memoryType, string storageUri, bytes32 parentHash, uint256 anchoredAt, bool revoked))",
  "function isValid(bytes32 contentHash) view returns (bool)",
  "function getAnchorsByOwner(bytes32 ownerDsid) view returns (bytes32[])",
  "function getLatestMerkleRoot() view returns (tuple(bytes32 root, uint256 blockNumber, uint256 anchorCount, uint256 timestamp))",
  "event MemoryAnchored(bytes32 indexed contentHash, bytes32 indexed ownerDsid, bytes32 agentDsid, uint8 memoryType, uint256 timestamp)"
];

// Types
export enum IdentityType {
  User = 0,
  Organization = 1,
  Agent = 2
}

export enum IdentityStatus {
  Active = 0,
  Suspended = 1,
  Revoked = 2
}

export enum AgentStatus {
  Active = 0,
  Deprecated = 1,
  Suspended = 2,
  Revoked = 3
}

export enum MemoryType {
  Conversation = 0,
  Document = 1,
  Embedding = 2,
  Composite = 3
}

export interface Identity {
  dsid: string;
  idType: IdentityType;
  status: IdentityStatus;
  publicKeyHash: string;
  evmAddress: string;
  metadataUri: string;
  createdAt: bigint;
  updatedAt: bigint;
  nonce: bigint;
}

export interface Agent {
  manifestHash: string;
  codeChecksum: string;
  sourceUri: string;
  manifestUri: string;
  ownerDsid: string;
  trustTier: number;
  status: AgentStatus;
  parentHash: string;
  category: string;
  publishedAt: bigint;
  updatedAt: bigint;
  executionCount: bigint;
}

export interface MemoryAnchor {
  contentHash: string;
  ownerDsid: string;
  agentDsid: string;
  memoryType: MemoryType;
  storageUri: string;
  parentHash: string;
  anchoredAt: bigint;
  revoked: boolean;
}

export interface ChainConfig {
  rpcUrl: string;
  identityRegistryAddress: string;
  agentRegistryAddress: string;
  memoryAnchorsAddress: string;
  privateKey?: string;
}

/**
 * Main Chain Client class
 */
export class ChainClient {
  private provider: Provider;
  private signer?: Wallet;
  private identityRegistry: Contract;
  private agentRegistry: Contract;
  private memoryAnchors: Contract;
  
  constructor(config: ChainConfig) {
    this.provider = new ethers.JsonRpcProvider(config.rpcUrl);
    
    if (config.privateKey) {
      this.signer = new Wallet(config.privateKey, this.provider);
    }
    
    const signerOrProvider = this.signer || this.provider;
    
    this.identityRegistry = new Contract(
      config.identityRegistryAddress,
      IDENTITY_REGISTRY_ABI,
      signerOrProvider
    );
    
    this.agentRegistry = new Contract(
      config.agentRegistryAddress,
      AGENT_REGISTRY_ABI,
      signerOrProvider
    );
    
    this.memoryAnchors = new Contract(
      config.memoryAnchorsAddress,
      MEMORY_ANCHORS_ABI,
      signerOrProvider
    );
  }
  
  // ============ Identity Functions ============
  
  /**
   * Register a new identity
   */
  async registerIdentity(
    dsid: string,
    idType: IdentityType,
    publicKeyHash: string,
    metadataUri: string
  ): Promise<string> {
    const tx = await this.identityRegistry.register(
      dsid,
      idType,
      publicKeyHash,
      metadataUri
    );
    const receipt = await tx.wait();
    return receipt.hash;
  }
  
  /**
   * Get identity by DSID
   */
  async getIdentity(dsid: string): Promise<Identity | null> {
    try {
      const result = await this.identityRegistry.getIdentity(dsid);
      if (result.createdAt === 0n) return null;
      
      return {
        dsid: result.dsid,
        idType: result.idType,
        status: result.status,
        publicKeyHash: result.publicKeyHash,
        evmAddress: result.evmAddress,
        metadataUri: result.metadataUri,
        createdAt: result.createdAt,
        updatedAt: result.updatedAt,
        nonce: result.nonce
      };
    } catch {
      return null;
    }
  }
  
  /**
   * Check if identity is active
   */
  async isIdentityActive(dsid: string): Promise<boolean> {
    return this.identityRegistry.isActive(dsid);
  }
  
  /**
   * Rotate identity key
   */
  async rotateKey(
    dsid: string,
    newPublicKeyHash: string,
    reason: string
  ): Promise<string> {
    const tx = await this.identityRegistry.rotateKey(dsid, newPublicKeyHash, reason);
    const receipt = await tx.wait();
    return receipt.hash;
  }
  
  // ============ Agent Functions ============
  
  /**
   * Publish a new agent
   */
  async publishAgent(
    manifestHash: string,
    codeChecksum: string,
    sourceUri: string,
    manifestUri: string,
    ownerDsid: string,
    trustTier: number,
    parentHash: string = ethers.ZeroHash,
    category: string = "general"
  ): Promise<string> {
    const tx = await this.agentRegistry.publish(
      manifestHash,
      codeChecksum,
      sourceUri,
      manifestUri,
      ownerDsid,
      trustTier,
      parentHash,
      category
    );
    const receipt = await tx.wait();
    return receipt.hash;
  }
  
  /**
   * Get agent by manifest hash
   */
  async getAgent(manifestHash: string): Promise<Agent | null> {
    try {
      const result = await this.agentRegistry.getAgent(manifestHash);
      if (result.publishedAt === 0n) return null;
      
      return {
        manifestHash: result.manifestHash,
        codeChecksum: result.codeChecksum,
        sourceUri: result.sourceUri,
        manifestUri: result.manifestUri,
        ownerDsid: result.ownerDsid,
        trustTier: result.trustTier,
        status: result.status,
        parentHash: result.parentHash,
        category: result.category,
        publishedAt: result.publishedAt,
        updatedAt: result.updatedAt,
        executionCount: result.executionCount
      };
    } catch {
      return null;
    }
  }
  
  /**
   * Check if agent is active
   */
  async isAgentActive(manifestHash: string): Promise<boolean> {
    return this.agentRegistry.isActive(manifestHash);
  }
  
  /**
   * Get agents by owner
   */
  async getAgentsByOwner(ownerDsid: string): Promise<string[]> {
    return this.agentRegistry.getAgentsByOwner(ownerDsid);
  }
  
  /**
   * Verify agent code checksum
   */
  async verifyAgentCode(manifestHash: string, checksum: string): Promise<boolean> {
    return this.agentRegistry.verifyCode(manifestHash, checksum);
  }
  
  // ============ Memory Functions ============
  
  /**
   * Anchor a memory hash
   */
  async anchorMemory(
    contentHash: string,
    ownerDsid: string,
    agentDsid: string = ethers.ZeroHash,
    memoryType: MemoryType = MemoryType.Conversation,
    storageUri: string = "",
    parentHash: string = ethers.ZeroHash
  ): Promise<string> {
    const tx = await this.memoryAnchors.anchor(
      contentHash,
      ownerDsid,
      agentDsid,
      memoryType,
      storageUri,
      parentHash
    );
    const receipt = await tx.wait();
    return receipt.hash;
  }
  
  /**
   * Anchor multiple memories in batch
   */
  async anchorMemoryBatch(
    contentHashes: string[],
    ownerDsid: string,
    agentDsid: string = ethers.ZeroHash,
    memoryType: MemoryType = MemoryType.Conversation,
    storageUri: string = ""
  ): Promise<string> {
    const tx = await this.memoryAnchors.anchorBatch(
      contentHashes,
      ownerDsid,
      agentDsid,
      memoryType,
      storageUri
    );
    const receipt = await tx.wait();
    return receipt.hash;
  }
  
  /**
   * Get memory anchor
   */
  async getMemoryAnchor(contentHash: string): Promise<MemoryAnchor | null> {
    try {
      const result = await this.memoryAnchors.getAnchor(contentHash);
      if (result.anchoredAt === 0n) return null;
      
      return {
        contentHash: result.contentHash,
        ownerDsid: result.ownerDsid,
        agentDsid: result.agentDsid,
        memoryType: result.memoryType,
        storageUri: result.storageUri,
        parentHash: result.parentHash,
        anchoredAt: result.anchoredAt,
        revoked: result.revoked
      };
    } catch {
      return null;
    }
  }
  
  /**
   * Check if memory anchor is valid
   */
  async isMemoryValid(contentHash: string): Promise<boolean> {
    return this.memoryAnchors.isValid(contentHash);
  }
  
  // ============ Utility Functions ============
  
  /**
   * Get current block number
   */
  async getBlockNumber(): Promise<number> {
    return this.provider.getBlockNumber();
  }
  
  /**
   * Get signer address
   */
  getAddress(): string | null {
    return this.signer?.address || null;
  }
  
  /**
   * Hash content to bytes32
   */
  static hashContent(content: string | Uint8Array): string {
    return ethers.keccak256(
      typeof content === 'string' ? ethers.toUtf8Bytes(content) : content
    );
  }
  
  /**
   * Generate DSID from public key and type
   */
  static generateDsid(publicKey: string, idType: IdentityType): string {
    const prefix = idType === IdentityType.User ? 'dsid-u-' :
                   idType === IdentityType.Organization ? 'dsid-o-' : 'dsid-a-';
    const hash = ethers.keccak256(ethers.toUtf8Bytes(publicKey));
    return ethers.keccak256(ethers.toUtf8Bytes(prefix + hash.slice(2, 18)));
  }
}

// Export default config for common chains
export const CHAIN_CONFIGS = {
  baseSepolia: {
    rpcUrl: 'https://sepolia.base.org',
    chainId: 84532
  },
  base: {
    rpcUrl: 'https://mainnet.base.org',
    chainId: 8453
  },
  localhost: {
    rpcUrl: 'http://127.0.0.1:8545',
    chainId: 31337
  }
};
